version: '3'

services:
  app_prog:
    build: EjercicioEstudianteProgramacion
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://est_prog:3306/cursos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USR: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      est_prog:
          condition: service_healthy
  est_prog:
    image: mysql:8.0.30
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: cursos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10